<!doctype html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="./Views/Styles/style4.css" />
<link rel="stylesheet" type="text/css" href="./Views/Styles/styleFooter.css"/>
<meta charset="UTF-8">
<title>[Why] - CGU</title>
</head>
<body>


<div id="cgu">
<h1>Conditions d'Utilisation</h1>

Ces Conditions d'Utilisation ("Conditions") régissent vos accès et utilisation des services, en ce compris notamment, nos différents sites Internet, les SMS, les API, les applications, les boutons, les notifications e-mail et les widgets, (les "Services" ou "[Why]"), et toute autre information, textes, graphiques, photos ou autres documents mis en ligne, téléchargés ou figurant dans les Services (collectivement dénommés les “Contenus”). Votre accès et votre utilisation des Services sont conditionnés à votre acceptation et le respect des présentes Conditions. En accédant aux Services ou en les utilisant, vous acceptez d'être lié par ces Conditions.
<h3>1. Conditions de base</h3>
Vous êtes responsable de votre utilisation des Services, des Contenus que vous publiez sur les Services, et de toute conséquence qui en découlerait. Les Contenus que vous soumettez, postez, ou affichez sont susceptibles d'être vus par d'autres utilisateurs des Services et au travers de services et sites web fournis par des tiers (vous pouvez vous rendre sur la page de profil pour contrôler qui peut accéder à vos Contenus). Vous ne devriez fournir que des Contenus que vous souhaitez partager avec d'autres conformément aux présentes Conditions.
Astuce : Ce que vous dites sur [Why] est visible partout dans le monde instantanément. Vous êtes ce que vous postez !
Vous pouvez utiliser les Services uniquement si vous avez la capacité de conclure un contrat avec [Why] et si vous n'êtes pas interdit de recevoir des services en vertu des lois Françaises ou d'autres lois applicables. Si vous acceptez ces Conditions et utilisez les Services au nom d'une entreprise, organisation, gouvernement ou autre entité juridique, vous déclarez et garantissez que vous êtes autorisé à le faire. Vous ne pouvez utiliser les Services qu'en conformité avec les présentes Conditions et toutes les lois, règles et règlements applicables qu'ils soient locaux, étatiques, nationaux et internationaux.
Les Services fournis par [Why] sont en constante évolution. La forme et la nature des Services fournis par [Why] peuvent changer à tout moment sans préavis. De plus, [Why] peut cesser (définitivement ou temporairement) de fournir les Services (ou toutes fonctionnalité inclue dans les Services), à vous ou aux utilisateurs en général, sans que [Why] puisse être en mesure de vous en aviser préalablement. Nous nous réservons également le droit de définir à notre seule discrétion des limites sur l'utilisation et le stockage, à tout moment et sans préavis.
<h3>2. Confidentialité</h3>
Vous comprenez qu'en utilisant nos Services, vous consentez à la suppression dès 7 jours d'existence de vos contenus et à la garantie de votre anonymat par [Why]. Dans le cadre de la fourniture des Services, nous pouvons être amenés à vous adresser certaines communications, telles que des annonces de service et des messages administratifs. Ces communications sont considérées comme partie intégrante des Services et de votre compte [Why], de sorte qu'il n'est pas certain que vous puissiez vous opposer à leur réception.
<h3>3. Les mots de passe</h3>
Vous êtes responsable de la protection du mot de passe que vous utilisez pour accéder aux Services et pour toutes les activités ou les actions faites après authentification avec votre mot de passe. Nous vous encourageons à utiliser pour votre compte des mots de passe forts (mots de passe constitués d'une combinaison de lettres majuscules et minuscules, de chiffres et de caractères spéciaux). [Why] ne saurait être responsable d'un quelconque dommage résultant d'un manquement de votre part sur ce qui précède.
<h3>4. Contenus avec les Services</h3>
Tous les Contenus, qu'il s'agisse des Contenus publiés ou communiqués à titre public ou privé, sont placés sous la seule responsabilité de la personne à l'origine de la communication de ces Contenus. [Why] n'est pas en mesure de surveiller ou de contrôler les Contenus postés au travers des Services, et ne peut engager sa responsabilité vis-à-vis de ces Contenus. Vous reconnaissez que toute utilisation des Contenus publiés au travers des Services, est à vos entiers risques et périls.
L'exhaustivité, la véracité, l'exactitude, ou la fiabilité des Contenus ou des informations publiés au travers des Services n'est en aucune manière assumée, supportée, revendiquée ou garantie par [Why]. [Why] ne soutient aucune opinion exprimée par l'intermédiaire des Services. Vous comprenez qu'en utilisant les Services, vous pouvez être exposé à des Contenus qui pourraient être offensants, blessants, inexacts ou inappropriés ou, dans certains cas, des messages mal titrés ou trompeurs. En aucun cas, [Why] ne pourra être tenue responsable de quelque manière que ce soit d'un quelconque dommage ou perte, de quelque nature que ce soit, résultant de l'utilisation des Contenus, y compris, de manière non exhaustive, en cas d'erreur ou omission dans les Contenus, que ces Contenus soient affichés, transmis par courrier électronique, transmis ou rendus disponibles d'une autre manière au moyen des Services ou diffusés autrement.
<h3>5. Vos droits</h3>
Vous conservez vos droits sur tous les Contenus que vous soumettez, postez ou publiez sur ou par l'intermédiaire des Services. 
[Why] applique un ensemble évolutif de règles sur la manière dont les partenaires de l'écosystème peuvent interagir avec vos Contenus. Ces règles ont été conçues pour mettre en place un écosystème ouvert, tenant compte de vos droits. Mais ce qui vous appartient vous appartient – vous restez propriétaire de vos Contenus (et vos photos font partie de ces Contenus).
Ces usages supplémentaires par [Why], ou d'autres sociétés, organisations ou individus en partenariat avec [Why], peuvent être faits sans compensation à votre égard en ce qui concerne les Contenus que vous soumettez, postez, transmettez ou rendez disponible au travers des Services.
Vous êtes responsable de l'utilisation que vous faites des Services, des Contenus que vous communiquez, et de toutes leurs conséquences, y compris de l'utilisation de vos Contenus par d'autres utilisateurs. Vous comprenez que vos Contenus peuvent faire l'objet d'une agrégation, d'une diffusion, d'une distribution ou d'une publication. Si vous ne disposez pas des droits nécessaires à la communication de ces Contenus pour une telle utilisation, vous engagez votre responsabilité.
[Why] ne saurait être tenue responsable des dommages résultant de l'utilisation de vos Contenus par [Why] faite en conformité avec les présentes Conditions. Vous déclarez et garantissez que vous disposez des droits, des pouvoirs et des autorisations nécessaires pour concéder les droits accordés en vertu des présentes sur les Contenus que vous soumettez.
<h3>6. Votre Licence d'utilisation des Services</h3>
[Why] vous concède une licence mondiale personnelle, gratuite, incessible, et non exclusive d'utiliser le logiciel mis à votre disposition par [Why] dans le cadre des Services. Cette licence a pour seul but de vous permettre d'utiliser et de bénéficier des Services fournis par [Why], en conformité avec les présentes Conditions.
<h3>7. Droits de [Why]</h3>
Tout droit, titre et intérêt dans les Services (à l'exclusion des Contenus communiqués par les utilisateurs) sont et restent la propriété exclusive de [Why] et de ses concédants. Les Services sont protégés au titre du droit d'auteur/Copyright, du droit des marques, et d'autres lois à la fois de France et des pays étrangers. Rien dans les présentes Conditions ne vous donne un droit d'utiliser le terme "[Why]" ou aucune des marques ni aucun des logos, noms de domaine et autres signes distinctifs de [Why]. Toute remarque, commentaire ou suggestion que vous pourriez soumettre concernant [Why] ou les Services est faite de manière libre et spontanée et nous serons libres d'utiliser ces réactions, commentaires ou suggestions comme bon nous semble et sans aucune obligation à votre égard.
<h3>8. Restrictions sur les Contenus et Utilisation des Services</h3>
Veuillez prendre connaissance des Règles de [Why] (qui font partie intégrante de ces Conditions d'Utilisation) afin de mieux comprendre ce qui est interdit dans le cadre de l'utilisation des Services.
Nous nous réservons le droit à tout moment, (mais sans que cela constitue une obligation) de supprimer ou de refuser de distribuer des Contenus sur les Services, de suspendre ou de résilier des comptes utilisateurs, et de récupérer des noms d'utilisateur, sans engager notre responsabilité à votre égard. 
Vous n'êtes pas autorisé à effectuer les actions suivantes en accédant ou en utilisant les Services : (i) accéder à des zones non-publiques des Services, des systèmes informatiques appartenant à [Why] ou à des systèmes techniques de fourniture des prestataires de [Why], ni à les utiliser ou les altérer, (ii) sonder, scanner ou tester la vulnérabilité de tout système ou réseau ou enfreindre ou contourner les mesures de sécurité ou d'authentification, (iii) accéder ou tenter d'accéder aux Services ou rechercher ou tenter de rechercher à travers les Services, par tout moyen (automatisé ou non), autrement que par l'interface publique fournie par [Why] (et seulement dans les limites des présentes conditions), sauf si vous avez été expressément autorisé à le faire aux termes d'un accord séparé avec [Why] (NOTE: indexer les Services est permis si cette opération est faite en conformité avec les dispositions comprises dans le fichier robots.txt. Néanmoins, aspirer les Services sans l'accord préalable de [Why] est expressément interdit), (iv) falsifier une en-tête de paquet TCP / IP ou toute partie de l'information dans l'en-tête d'un courriel ou post, ou utiliser d'une quelconque manière les Services pour envoyer des informations altérées, trompeuses ou dont la source est faussement identifiée, ou (v) perturber ou interrompre (ou tenter de le faire) l'accès de tout utilisateur, hôte ou réseau, en ce compris notamment, l'envoi d'un virus, les opérations de type overloading, flooding, spamming, mail-bombing à l'encontre des Services, ou en scriptant la création des Contenus manière à interférer avec le Service ou créer une charge indue sur les Services.
<h3>9. Politique de Copyright</h3>
[Why] respecte les droits de propriété intellectuelle d'autrui et s'attend à ce que les utilisateurs des Services en fassent de même. Nous répondons aux notifications relatives à une violation des droits d'auteur dès lors qu'elles sont conformes à la législation applicable et nous sont adressées correctement. Si vous pensez que vos Contenus ont été reproduits ou diffusés de manière contrefaisante, veuillez nous fournir les informations suivantes : (i) une signature physique ou électronique du titulaire de droits ou d'une personne autorisée à agir en son nom, (ii) l'identification de l'œuvre protégée qui selon vous a fait l'objet d'une utilisation contrefaisante, (iii) l'identification des contenus qui selon vous porte atteinte à ces droits ou fait l'objet d'activités contrefaisantes et qui doit être enlevé ou dont l'accès doit être désactivé, ainsi que des renseignements raisonnablement suffisants pour nous permettre de localiser ces contenus, (iv) vos coordonnées, notamment vos adresse, numéro de téléphone et une adresse e-mail, (v) une déclaration de votre part selon laquelle vous estimez de bonne foi que l'utilisation des contenus en cause n'est pas autorisée par le titulaire de droits, son mandataire ou la loi, et (vi) une déclaration selon laquelle les informations contenues dans la notification sont exactes et, sous peine de parjure, que vous êtes autorisé à agir pour le compte du titulaire de droits.
Nous nous réservons le droit de supprimer les Contenus présumés contrefaisants sans préavis, à notre seule discrétion et sans engager notre responsabilité envers vous. Lorsque les circonstances le justifient, [Why] sera également en droit résilier le compte d'un utilisateur si l'utilisateur est considéré à plusieurs reprises comme contrefacteur. 
<h3>10. Résiliation </h3>
Les Conditions continueront à s'appliquer jusqu'à leur résiliation par vous ou par [Why] selon les termes suivants.
Vous pouvez mettre fin à votre accord avec [Why] à tout moment pour quelque raison que ce soit par la suppression de vos comptes et mettre fin à votre utilisation des Services.
Nous pouvons suspendre ou résilier vos comptes ou cesser de vous fournir tout ou partie des Services à tout moment pour quelque raison que ce soit, notamment si nous avons des motifs raisonnables de croire que : (i) vous avez violé les présentes Conditions, (ii) vous créez un risque juridique à notre encontre, ou (iii) la mise à disposition des Services pour votre usage n'est plus économiquement viable. Nous mettrons en œuvre des moyens raisonnables pour vous en aviser, à l'adresse e-mail associée à votre compte ou lorsque vous tenterez d'accéder à votre compte.
Dans tous les cas précités, les Conditions seront résiliées, ce qui inclue, sans limitation, la licence d'utilisation des Services dont vous bénéficiez, sauf pour les sections suivantes qui continuent de s'appliquer : 4, 5, 7, 8, 10, 11 et 12.
Rien dans la présente section n'affecte le droit de [Why] de modifier, de limiter ou d'arrêter la mise à disposition des Services, sans préavis, tel que prévu ci-dessus dans la section 1.
<h3>11. Avertissements et limitations de responsabilité </h3>
Veuillez lire attentivement cette section car elle a pour objet de limiter la responsabilité de [Why] et de ses sociétés mère, sociétés affiliées, dirigeants, employés, mandataires, partenaires et concédants (collectivement, les "Entités [Why]"). Chacune des sous-sections ci-dessous s'applique dans la limite la plus étendue autorisée par des dispositions légales applicables. Certaines lois nationales n'autorisent pas l'exclusion des garanties implicites ou les limitations de responsabilité dans les contrats, et en conséquence les dispositions de cette section peuvent ne pas s'appliquer à vous. Rien dans la présente section n'est destiné à limiter les droits que vous pourriez avoir qui ne peuvent être légalement limités.
A. Les Services sont fournis "EN L'ETAT".
Vous utilisez et accédez aux Services et aux Contenus à vos entiers risques et périls. Vous comprenez et acceptez que les Services vous sont fournis "EN L'ETAT" et "TELS QUE DISPONIBLES". Sans préjudice de ce qui précède, et dans les limites les plus étendues autorisées par la loi applicable, les ENTITÉS [WHY] EXCLUENT TOUTES GARANTIES, EXPRESSES OU IMPLICITES, DE QUALITE MARCHANDE, D'ADEQUATION A UN USAGE PARTICULIER OU GARANTIES D'EVICTION.
Les Entités de [Why] ne donnent aucune garantie et déclinent toute responsabilité s'agissant : (i) de l'exhaustivité, l'exactitude, la disponibilité, la ponctualité, la sécurité ou la fiabilité des Services ou des contenus, (ii) des dommages subis par votre système informatique, ou des pertes de données, ou autres dommages résultant de votre accès ou utilisation des Services ou des Contenus, (iii) de la suppression des Contenus et autres communications gérés par les Services ou de l'échec de leur conservation ou transmission, et (iv) de savoir si les Services répondent à vos besoins ou seront disponibles de manière ininterrompue, sécurisée ou exempte d'erreurs. Aucun conseil et aucune information, qu'ils soient oraux ou écrits, obtenus à partir des Entités [Why] ou via les Services, ne créé une quelconque garantie dès lors qu'ils ne sont pas expressément mentionnés dans les Conditions.
B. Liens
Les Services peuvent contenir des liens vers des sites ou des ressources de tiers. Vous reconnaissez et acceptez que les Entités [Why] ne sont pas responsables : (i) de la disponibilité ou de l'exactitude de ces sites ou ressources, ou (ii) du contenu, des produits ou des services disponibles sur ou à partir de ces sites ou ressources. Aucun lien vers ces sites ou ressources n'implique l'approbation par les Entités [Why] de ces sites ou ressources ou de leur contenu, des produits ou des services offerts par ces sites ou ressources. L'utilisation de tels sites ou ressources se fait sous votre seule responsabilité et à vos entiers risques et périls.
C. Limitation de responsabilité
DANS LA LIMITE LA PLUS ETENDUE AUTORISEE PAR LA LOI APPLICABLE, LES ENTITÉS [WHY] EXCLUENT TOUTE RESPONSABILITE POUR TOUS DOMMAGES INDIRECTS, ACCESSOIRES, SPÉCIAUX, CONSEQUENTIELS OU PUNITIFS, OU POUR TOUTE PERTE DE PROFITS OU DE REVENUS, QU'ILS SOIENT SUBIS DIRECTEMENT OU INDIRECTEMENT, AINSI QUE POUR TOUTE PERTE DE DONNÉES, D'UTILISATION, DE REPUTATION OU GOODWILL, OU AUTRES PERTES INTANGIBLES, RESULTANT (i) DE VOTRE ACCES AUX SERVICES OU DE LEUR UTILISATION, OU DE L'INCAPACITE D'ACCEDER AUX SERVICES OU DE LES UTILISER, (ii) DE TOUT COMPORTEMENT OU CONTENUS DE TIERS SUR LES SERVICES, Y COMPRIS, SANS LIMITATION, TOUTE CONDUITE DIFFAMATOIRE, OFFENSANTE OU ILLEGALE D'AUTRES UTILISATEURS OU DE TIERS, (iii) DES CONTENUS OBTENUS GRACE AUX SERVICES, OU (iv) DE TOUT ACCES, UTILISATION, ALTERATION DE VOS TRANSMISSIONS OU CONTENUS.
EN AUCUN CAS LE MONTANT TOTAL DES DOMMAGES INTERETS AUXQUELS LES ENTITES [WHY] POURRAIENT ETRE CONDAMNEES AU TITRE DE LEUR RESPONSABILITE NE POURRA DEPASSER LE MONTANT LE PLUS ELEVE ENTRE CENT EUROS ET LES SOMMES QUE VOUS AVEZ VERSEES A [WHY], LE CAS ECHEANT, DURANT LES SIX DERNIERS MOIS POUR LES SERVICES À L'ORIGINE DE LA DEMANDE.
LES LIMITES STIPULEES DANS CETTE SECTION S'APPLIQUENT QUEL QUE SOIT LE FONDEMENT JURIDIQUE SUR LEQUEL LA RESPONSABILITE EST RECHERCHEE, NOTAMMENT CONTRACTUEL, DELICTUEL (Y COMPRIS LA NÉGLIGENCE) OU AUTRE, ET QUE LES ENTITÉS [WHY] AIENT ETE OU NON AVERTIES DE LA POSSIBILITE DE TELS DOMMAGES ET MÊME SI LES REPARATIONS PREVUES DANS LE CADRE DES PRESENTES N'ONT PAS ATTEINT LEUR OBJECTIF ESSENTIEL.
<h3>12. Conditions générales</h3>
A. Renonciation et divisibilité
Le fait que [Why] ne cherche pas à se prévaloir d'un droit ou d'une disposition des présentes Conditions ne doit pas être considéré comme une renonciation à ce droit ou à cette disposition. Dans le cas où une disposition de ces Conditions serait jugée invalide ou inapplicable, cette disposition sera limitée ou supprimée dans la stricte mesure nécessaire, et les dispositions restantes de ces Conditions resteront pleinement vigueur.
B. Loi applicable et compétence
Ces Conditions et toute action judiciaire engagée en relation avec ces Conditions sont régies par les lois de Françaises sans considération et sans faire application des dispositions légales de votre Etat ou de votre pays de résidence relatives aux conflits de lois. Vous acceptez la compétence matérielle et territoriale de ces tribunaux et renoncez à toute objection à ce titre.
C. Intégralité de l'accord
Ces Conditions constituent l'intégralité de l'accord conclu entre [Why] et vous concernant les Services (à l'exclusion des services pour lesquels vous avez conclu un accord distinct avec [Why] incluant ou excluant expressément les présentes Conditions). Les présentes Conditions annulent et remplacent tous les accords antérieurs entre [Why] et vous concernant les Services. A l'exception des sociétés du groupe dont [Why] est la société-mère, aucune personne ou société ne sera considérée comme un tiers bénéficiaire des présentes Conditions.
Ces Conditions peuvent faire l'objet de modifications à tout moment. Si nous jugeons que ces modifications sont substantielles, nous les porterons à votre connaissance via une mise à jour. En continuant d'accéder ou d'utiliser les Services après l'entrée en vigueur de ces modifications, vous acceptez d'être contractuellement liés par ces nouvelles Conditions d'utilisations.
Ces services sont gérés et fournis par [Why].






</div>
<div id="cadrage-f">
	<div id="footer">
		<a href='contactForm.php'><span id="b-left">Contact</span></a>
		<a href='faq.php'><span id="b-middle">Faq</span></a>
		<a href='cgu.php'><span id="b-right">CGU</span></a>
	</div>
</div>


</body>
</html>